### ISSUE TITLE
sqflite找不到

### ISSUE THREAD

**Issue by zjf1165** [xiaojia21190/ZY_Player_flutter#10]
CocoaPods could not find compatible versions for pod "sqflite":
      In Podfile:
        sqflite (from `.symlinks/plugins/sqflite/ios`)
    Specs satisfying the `sqflite (from `.symlinks/plugins/sqflite/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by xiaojia21190** [comment]
update code
