### ISSUE TITLE
TV版

### ISSUE THREAD

**Issue by Pantyhose-X** [xiaojia21190/ZY_Player_flutter#12]
希望有TV版 android 4.4.

TV版 android 4.4 方便父母们追剧

**Comment by xiaojia21190** [comment]
不好写啊

**Comment by Pantyhose-X** [comment]
> 不好写啊

使用[flutter](https://flutter.dev/)

**Comment by nnianhou-** [comment]
> > 不好写啊
> 
> [flutter](https://flutter.dev/)
> 样本
> https://github.com/android/tv-samples
> https://medium.com/@pcmushthaq/adding-android-tv-support-to-your-flutter-app-dcc5c1196231
> https://github.com/hanniiel/flutter_tv

哈哈，可以，样本都给找好了
我这怎么跑不起来，缺失一些东西。

**Comment by xiaojia21190** [comment]
好的,我先看看.. 
是的,有一些文件还没提交

**Comment by xiaojia21190** [comment]
@Pantyhose-X  确实是可以写的. 我最近尝试一下,看能不能写出来

**Comment by Pantyhose-X** [comment]
> @Pantyhose-X 确实是可以写的. 我最近尝试一下,看能不能写出来, 我也有这方面的需求,之前是写了个投屏,所以TV版本就搁置了.

建议你基于[SmartTubeNext](https://github.com/yuliskov/SmartTubeNext) 重头写，你要写的东西太多了
