### ISSUE TITLE
编译错误，提示缺少文件

### ISSUE THREAD

**Issue by zyjia** [xiaojia21190/ZY_Player_flutter#13]
小白第一次使用 ,提示缺少文件
The plugins `flutter_screen, image_gallery_saver, ota_update` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Launching lib\main.dart on EDA51 in debug mode...
Running Gradle task 'assembleDebug'...
lib/home/home_page.dart:22:8: Error: Error when reading 'lib/util/hex_color.dart': 系统找不到指定的文件�?

import 'package:ZY_Player_flutter/util/hex_color.dart';
       ^
lib/home/home_page.dart:27:8: Error: Error when reading 'lib/widgets/bubble_tab_indicator.dart': 系统找不到指定的文件�?

import 'package:ZY_Player_flutter/widgets/bubble_tab_indicator.dart';
       ^
lib/home/home_page.dart:427:42: Error: The method 'BubbleTabIndicator' isn't defined for the class '_HomeState'.
 - '_HomeState' is from 'package:ZY_Player_flutter/home/home_page.dart' ('lib/home/home_page.dart').
Try correcting the name to the name of an existing method, or defining a method named 'BubbleTabIndicator'.
                              indicator: BubbleTabIndicator(),
                                         ^^^^^^^^^^^^^^^^^^
lib/home/home_page.dart:459:42: Error: The method 'BubbleTabIndicator' isn't defined for the class '_HomeState'.
 - '_HomeState' is from 'package:ZY_Player_flutter/home/home_page.dart' ('lib/home/home_page.dart').
Try correcting the name to the name of an existing method, or defining a method named 'BubbleTabIndicator'.
                              indicator: BubbleTabIndicator(),
                                         ^^^^^^^^^^^^^^^^^^
lib/home/home_page.dart:527:34: Error: The method 'HexColor' isn't defined for the class '_HomeState'.
 - '_HomeState' is from 'package:ZY_Player_flutter/home/home_page.dart' ('lib/home/home_page.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HexColor'.
                backgroundColor: HexColor('#FFA400'),
                                 ^^^^^^^^
lib/home/home_page.dart:586:46: Error: The method 'HexColor' isn't defined for the class '_HomeState'.
 - '_HomeState' is from 'package:ZY_Player_flutter/home/home_page.dart' ('lib/home/home_page.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HexColor'.
                    final color = isActive ? HexColor('#FFA400') : Colors.white;
                                             ^^^^^^^^
lib/home/home_page.dart:603:36: Error: The method 'HexColor' isn't defined for the class '_HomeState'.
 - '_HomeState' is from 'package:ZY_Player_flutter/home/home_page.dart' ('lib/home/home_page.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HexColor'.
                  backgroundColor: HexColor('#373A36'),
                                   ^^^^^^^^
lib/home/home_page.dart:605:32: Error: The method 'HexColor' isn't defined for the class '_HomeState'.
 - '_HomeState' is from 'package:ZY_Player_flutter/home/home_page.dart' ('lib/home/home_page.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HexColor'.
                  splashColor: HexColor('#FFA400'),
                               ^^^^^^^^
lib/login/page/login_page.dart:78:28: Error: Method not found: 'Utils.getUniqueId'.
    var uuid = await Utils.getUniqueId();
                           ^^^^^^^^^^^
lib/provider/app_state_provider.dart:129:46: Error: Too few positional arguments: 1 required, 0 given.
      ApplicationEvent.event.fire(DeviceEvent());
                                             ^
lib/event/event_model.dart:18:3: Context: Found this candidate, but the arguments don't match.
  DeviceEvent(this.device);
  ^^^^^^^^^^^
lib/login/page/register_page.dart:81:28: Error: Method not found: 'Utils.getUniqueId'.
    var uuid = await Utils.getUniqueId();
                           ^^^^^^^^^^^
lib/player/widget/zhibo_list_page.dart:78:62: Error: The getter 'cover' isn't defined for the class 'M3uResult'.
 - 'M3uResult' is from 'package:ZY_Player_flutter/model/zhibo_resource.dart' ('lib/model/zhibo_resource.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'cover'.
                              _zhiboListProvider.list[index].cover,
                                                             ^^^^^
lib/player/page/player_detail_page.dart:80:43: Error: Too few positional arguments: 2 required, 1 given.
    _collectProvider.setListDetailResource("collcetPlayer");
                                          ^
lib/player/page/zhibo_detail_page.dart:61:43: Error: Too few positional arguments: 2 required, 1 given.
    _collectProvider.setListDetailResource("collcetPlayer");
                                          ^
lib/tingshu/page/tingshu_detail_page.dart:59:43: Error: Too few positional arguments: 2 required, 1 given.
    _collectProvider.setListDetailResource("collcetTingshu");
                                   ^
lib/tingshu/page/tingshu_detail_page.dart:164:37: Error: The getter 'list' isn't defined for the class 'CollectProvider'.
 - 'CollectProvider' is from 'package:ZY_Player_flutter/Collect/provider/collect_provider.dart' ('lib/Collect/provider/collect_provider.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'list'.
      var result = _collectProvider.list.where((element) => element.url == data.url).toList();
                                    ^^^^
lib/tingshu/page/tingshu_detail_page.dart:288:46: Error: The method 'removeTingshu' isn't defined for the class 'CollectProvider'.
 - 'CollectProvider' is from 'package:ZY_Player_flutter/Collect/provider/collect_provider.dart' ('lib/Collect/provider/collect_provider.dart').
Try correcting the name to the name of an existing method, or defining a method named 'removeTingshu'.
                            _collectProvider.removeTingshu(_tingShuProvider.tingshudetail.url);
                                             ^^^^^^^^^^^^^
lib/tingshu/page/tingshu_detail_page.dart:291:46: Error: The method 'addTingshu' isn't defined for the class 'CollectProvider'.
 - 'CollectProvider' is from 'package:ZY_Player_flutter/Collect/provider/collect_provider.dart' ('lib/Collect/provider/collect_provider.dart').
Try correcting the name to the name of an existing method, or defining a method named 'addTingshu'.
                            _collectProvider.addTingshu(
                                             ^^^^^^^^^^
/D:/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/wakelock_platform_interface-0.2.0/lib/messages.dart:100:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/Android/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler(null);
                ^^^^^^^^^^^^^^^^^^^^^
/D:/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/wakelock_platform_interface-0.2.0/lib/messages.dart:102:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/Android/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler((dynamic message) async {
                ^^^^^^^^^^^^^^^^^^^^^
/D:/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/wakelock_platform_interface-0.2.0/lib/messages.dart:114:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/Android/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler(null);
                ^^^^^^^^^^^^^^^^^^^^^
/D:/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/wakelock_platform_interface-0.2.0/lib/messages.dart:116:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/Android/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler((dynamic message) async {
                ^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Android\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Android\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by xiaojia21190** [comment]
使用最新版本看看

**Comment by zyjia** [comment]
感谢，已经编译出来了，可能是因为新版本的sdk关系，需要注意的是 IntelliJ/Android Studio#
"Edit Configurations" (在RUN配置里) → "Additional run args" 添加
--no-sound-null-safety
要登录，是否要是后台，服务器地址在哪里？

**Comment by xiaojia21190** [comment]
是需要后台的，联系作者，详聊。
