### ISSUE TITLE
[!] Invalid `Podfile` file: cannot load such file -- /Users/henry/Documents/Flutter/flutter_sdk/flutter/packages/flutter_tools/bin/podhelper.

### ISSUE THREAD

**Issue by henry0510** [xiaojia21190/ZY_Player_flutter#3]
HenrydeMacBook-Pro:ios henry$ pod install

[!] Invalid `Podfile` file: cannot load such file -- /Users/henry/Documents/Flutter/flutter_sdk/flutter/packages/flutter_tools/bin/podhelper.

 #  from /Users/henry/Documents/Flutter/flutter_project/ZY_Player_flutter/ios/Podfile:26
 #  -------------------------------------------
 #  
 >  require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
 #  
 #  -------------------------------------------

**Comment by xiaojia21190** [comment]
@henry0510  你下载了，最新的sdk了吗？下载完之后flutter clean 一下，然后在编译。

**Comment by xiaojia21190** [comment]
@henry0510  https://github.com/flutter/flutter/issues/59522  这个官方的问题，你看一下，这里有解决方法！
