### ISSUE TITLE
点击播放一片空白

### ISSUE THREAD

**Issue by L1cardo** [xiaojia21190/ZY_Player_flutter#4]
小米 6
荣耀 20
均这样

**Comment by xiaojia21190** [comment]
@L1cardo 可能是内置webview浏览器的问题。官方内置的兼容性不是很好！

**Comment by L1cardo** [comment]
> @L1cardo 可能是内置webview浏览器的问题。官方内置的兼容性不是很好！

我看到 1.0.2 版本新增了外部浏览器播放的功能，请问在哪里呀，没找到

**Comment by xiaojia21190** [comment]
> > @L1cardo 可能是内置webview浏览器的问题。官方内置的兼容性不是很好！
> 
> 我看到 1.1.0 版本新增了外部浏览器播放的功能，请问在哪里呀，没找到

请看最新版本的releass，已经修复 [https://github.com/xiaojia21190/ZY_Player_flutter/releases/download/1.1.1/app-release.apk](url)
