### ISSUE TITLE
遥控器的确认按钮能适配一下么？其他操作遥控器似乎都能支持

### ISSUE THREAD

**Issue by larchsis** [xiaojia21190/ZY_Player_flutter#5]
在盒子上装了一下，上下左右退出之类都有效果，就是确认没效果。也就是没办法点击……能适配一下么？感谢。

**Comment by xiaojia21190** [comment]
@larchsis 能给录一个视频吗？

**Comment by xiaojia21190** [comment]
@larchsis 你可以试试这个包，麻烦使用完了，给个反馈，因为我本地没有对应的设备。
[app-release.zip](https://github.com/xiaojia21190/ZY_Player_flutter/files/5281534/app-release.zip)

**Comment by larchsis** [comment]
感谢，提供的版本已经试用反馈几个问题：（盒子可安装app-armeabi-v7a-release.apk及app-release.apk）
1. 遥控器点击已经可用，所以能进一步测试各个功能；
2. 搜索功能能用，也能查询出结果，但是播放时一直转圈无法正常播放；
3. 下方3个页面进入后都是空白没有内容显示；
4. 片子详情页面右上角的点击收藏，多次点击就多次重复收藏；
是不是盒子的网络访问和手机上不同？如果麻烦的话就算了，我晚点试试这个临时版本手机上的情况，能不能正常使用网络。

感谢提供版本。

**Comment by xiaojia21190** [comment]
可以试一下，最新版的
