### ISSUE TITLE
1.1.6使用情况反馈

### ISSUE THREAD

**Issue by larchsis** [xiaojia21190/ZY_Player_flutter#6]
测试环境：
1. 安卓4.4.2
2. 无线网络（网络测试正常，能打开bing）

问题：
1. 安装1.1.6版本，第一次打开后影视页显示无网络连接，切换其他几个页面白板；
2. 关闭后约10分钟后再次打开，影视页有内容出现，切换其他页面白板；
3. 随便选择首页的影片播放，有进度有声音，图像黑屏无法显示（这个可能是老安卓平板渲染问题）；
4. 点击影视页搜索，搜索“元龙”有结果反馈，播放时情况同上；

测试环境
1. 安卓盒子，版本号不确定
2. 有线网络（网络测试正常，斗鱼tv能正常看直播）

问题：
1. 安装1.1.6版本，第一次打开后影视页显示无网络连接，切换其他几个页面白板；
2. 关闭后约10分钟后再次打开，影视页有内容出现，切换其他页面白板；
3. 影视页上的点击搜索无法用遥控器的方向选中，所以无法确认操作；
4. 其他页面上的搜索框能选中，能搜索，能选中结果，能进入详情。

正好有空就测试了一下，感谢提供应用。

**Comment by xiaojia21190** [comment]
谢谢。
